### PR TITLE
[WIP] Show related docstrings in message panel

### LINKED ISSUE #181: Add functionality to show method signature on-demand
Hi,

I'd like to request next feature. In plugin settings there is an option to put none, required or all arguments. Is it possible to show method signature on request in some popup window?

Sometimes is faster to look into signature than scroll all available parameters in the list.

### PR DESCRIPTION
**Pull request by sadovnychyi**
sample

We can get a docstring of object which is currently under a cursor using go to definition.
Another option is to only lookup for docstrings when you select entire object name.
But probably lookup of each object under a cursor should be ok. Need to limit the scopes so we will not call it on non-related stuff.

Another option is to only activate it on specific command call.

https://atom.io/docs/api/v1.5.3/Cursor#instance-onDidChangePosition

Closes #181

https://github.com/atom/atom/issues/9936

### CODE REVIEW

**Comment by pchomik** [comment]
Proposition look promising. I installed doc-panel branch but there is only panel example without real logic.
What I may suggest is that panel should disappear after pressing Esc key.

**Comment by sadovnychyi** [comment]
Nothing still there, just trying to collect some ideas.

**Comment by pchomik** [comment]
For me looks ok. I'm waiting for implementation.

**Comment by pchomik** [comment]
Any update on this? Can I help you?

**Comment by sadovnychyi** [comment]
Sorry, I simply don't have time for this right now. Will come back to this
in the future.

**Comment by sadovnychyi** [comment]
Playing around with [markers](https://atom.io/docs/api/v1.8.0/TextEditor#instance-decorateMarkerLayer) I come up with another proof of work:
sample

It's not really usable, but it will work for testing purposes.

- [ ] It will conflict with autocomplete overlay. And linter overlay. Ideas?
- [ ] It will probably spawn a lot of them if you have multiple cursors 
- [ ] No styling. How to make it look nice on any (dark or light) theme color?
- [ ] We use go-to-definition right now and show doc string from the first definition if any. We could expand this to show doc strings for call signatures as well. More ideas?

**Pull request merged**
