### PR TITLE
[WIP] Add hyperclick support for go-to-definition

### PR DESCRIPTION
**Pull request by sadovnychyi**
[Hyperclick](https://atom.io/packages/hyperclick) can use autocomplete-python as one of providers. 

sample

Click on anything while holding CMD to trigger go-to-definition.

- [ ] Does not works great with hyperclick's default keystrokes since CMD used for multi cursors
- [ ] It allows to click on anything, even on keywords. We should filter them out somehow, likely by using scopes

@eMerzh check this out, as this was your idea.

### CODE REVIEW

**Comment by eMerzh** [comment]
Hi,
not sure how to test it :confused:

**Comment by sadovnychyi** [comment]
Install hyperclick, clone this branch and put it into your atom's packages directory. (by temporary replacing live version)

```
git clone -b hyperclick-support git@github.com:sadovnychyi/autocomplete-python.git
```

**Comment by eMerzh** [comment]
mmmh i got the same error as ... #98 unable test then... :s i tryied to uninstall and reinstall but didn't work.
:-/

**Comment by sadovnychyi** [comment]
Try to run `apm install` from package directory.

**Comment by eMerzh** [comment]
nice, works great now ...
 :+1: 
i've tested it for a few minutes, and everything seems fine ..;
the only remarks (not really a bug...) that i have is, when you have something like 
in filea.py 
```python
class MyClass(object):
    def __init(self, foo=None):
       pass
   def bark(self):
       pass
```

then in fileb.py:
```python
from filea import MyClass

bar = MyClass()
bar.bark()
```
on the last line, if you cmd click on bark, it goes directly to filea on the "bark" method, but if you click on "MyClass()" it first goes to the import then if you click again on "MyClass" then it goes to filea.py
i'd prefer going directly to the class definition...

The behavior seems logical but less convenient :)

**Comment by sadovnychyi** [comment]
Agree with you, but this is how Jedi works. Not sure that I can change it.

**Comment by patrys** [comment]
Jedi allows asking for the root definition of a symbol but it's rather slow and breaks another useful feature: skipping to where a variable was assigned rather to where the assigned value was defined.

**Pull request merged**
