### PR TITLE
Implement go-to-definition

### PR DESCRIPTION
**Pull request by patrys**
Now with a select box that allows user to select the symbol to jump to.

Maybe related: atom/symbols-view#95

### CODE REVIEW

**Comment by patrys** [comment]
Added a nice UI.

**Comment by sadovnychyi** [comment]
Thanks for this feature!

I'll test/merge/release it tomorrow.

**Comment by ferdynice** [comment]
Nice feature. Two questions/comments:

* What is the difference between definition and declaration? Because the built-in symbol browser uses go-to-definition and return-from-definition (resp using ctrl-alt-down and ctrl-down-up) which is a pretty handy way to navigate in the project. This does not seem to work with 'definition'. Therefore, what advantage has 'definition' over 'declaration'?
* If there is only one entry found, why would you still show the dialog box instead of going straight away to the entry?

**Comment by patrys** [comment]
This is just the initial implementation and there is room for improvement but I thought the feature was useful enough as it is.

As for “go to declaration”, it is provided by the `symbols-view` package. Unfortunately for the time being (see linked pull request in the first comment) there is no way for `autocomplete-python` to integrate with it.

**Comment by ferdynice** [comment]
You are absolutely right with regard to the useful-enough approach. Those were just some minor remarks.

**Comment by patrys** [comment]
If you open separate bugs for these tweaks, I will try to get them implemented in the next couple of days.

**Comment by ferdynice** [comment]
Alright, done.

**Comment by MichaelAquilina** [comment]
Hey guys, Just noticed this pull request and just wanted to let you know that this feature was already available for a while on my (relatively used) plugin called [Python Tools](https://github.com/michaelaquilina/python-tools). The intention I have with my plugin is to add any missing functionality to atom that typically come in IDEs like PyCharm.

I had initially thought of creating a goto definition pull request for this plugin instead of creating my plugin but thought it didnt fit in well within the scope of this project. Users wont really expect to be able functionality like "goto definition" from a package that is about providing auto complete functionality for the Python grammar.

I wanted to discuss and hear your thoughts on whether you think its an issue, whether you feel it's relevant to separate out functionality (so users only download what they expect) or if you feel we should somehow merge the two plugins?

Great work on the pull requests regardless! :)

**Comment by sadovnychyi** [comment]
I'm pretty sure it's should live in one package since both of this plugins
use Jedi, and if we will separate them – we will have to spawn two Jedi
processes.

**Comment by MichaelAquilina** [comment]
Having two Jedi processes is not a huge deal IMO, they're both very lightweight in terms of memory and only use CPU when data is sent (due to blocking IO).

**Pull request merged**
