### PR TITLE
[WIP] Autocomplete function arguments inside of functions

### PR DESCRIPTION
**Pull request by sadovnychyi**
- [x] Offer function arguments as completion options when inside of functions
- [x] Filter out non-relevant to current request arguments
- [x] Choose proper completion type from autocomplete-plus API. Currently "property" is used.
- [x] Autocomplete function arguments only after typing "(" following by callable

image

### CODE REVIEW

**Comment by patrys** [comment]
I have a local branch for autocompleting full signatures immediately after a `(` but there's a conflict between bracket matcher and autocompleting that prevents the dropdown from being shown.

**Comment by sadovnychyi** [comment]
I think we should somehow automatically append all arguments (according to package settings) once "(" is typed, without showing any options. This is what we are doing right now when function with arguments is selected, but there are really many cases when we don't want to complete arguments. So only do it when "(" is typed. 

But I'm not sure if it's possible to complete without showing the dropdown.

**Comment by patrys** [comment]
I also have another branch that makes the entire param list a snippet in this form: `function${1:(${2:parameter}, ${3:other_param})}$0`. This allows you to immediately press delete after accepting a suggestion to remove the param but there's a bug in how autocomplete parses the snippet for display when a template contains another template.

**Comment by patrys** [comment]
I have some more improvements for this in the oven.

**Comment by sadovnychyi** [comment]
Show it!

**Comment by patrys** [comment]
Do we want to keep filtering by prefix or should we let `fuzzaldrin` do the filtering (this seems to be preferable for autocomplete)?

**Comment by sadovnychyi** [comment]
Yeah, I didn't know about it. Will you fix it with another PR?

**Pull request merged**
